// Copyright (c) 2026 Michael D Henderson. All rights reserved.

// Package store is single-world SQLite persistence: one file, one world, one
// game.
//
// It imports wgva and config, and wgva imports neither, which is what makes
// "persistence is not in the core" a fact of the build rather than a review
// convention — Go's import cycle rule refuses the other direction with no lint
// and no reviewer. render is a sibling and is not imported here either: a
// renderer that could open a database would be a renderer that could be handed a
// world rather than a viewport, so the command does the loading and the two meet
// in render.RenderPlayer, in pixels.
//
// Nothing in this package generates a tile. There is no tile cache and building
// one is not deferred work to pick up later — WGVB measured and the answer was
// no; DESIGN.md 27.6 is the record.
//
// See DESIGN.md 27 and appendix C.
package store

import (
	"context"
	"errors"
	"fmt"

	"zombiezen.com/go/sqlite"
	"zombiezen.com/go/sqlite/sqlitemigration"
	"zombiezen.com/go/sqlite/sqlitex"
)

// ApplicationID is written to every WGVA database as PRAGMA application_id.
//
// It is ASCII "WGVA", and it deliberately differs from WGVB's 0x57475642 by one
// byte. A WGVB file must be rejected by a WGVA binary at the first gate, and
// vice versa: the two are different world formats that happen to describe the
// same kind of world, and opening one as the other would read a seed out of a
// row that means something else.
const ApplicationID int32 = 0x57475641

// The opening gates of DESIGN.md 27.5, one sentinel each.
//
// A test that compares an error's Error() string is a test that passes while the
// gate is wrong, so every assertion in this package's tests — and in every
// caller's — is errors.Is against one of these. DESIGN.md 19.1 and 30.11.
var (
	// ErrNoWorld is returned for an absent or empty file. Gate 1's other half:
	// an empty file is initialized only by `wgva-world create`, and every other
	// tool refuses it rather than treating a typo in a path as an invitation.
	ErrNoWorld = errors.New("no world file there")

	// ErrWorldExists is returned by Create for a path that already exists.
	// There is no --force: removing a world is something a person does
	// deliberately, with rm.
	ErrWorldExists = errors.New("a file already exists there")

	// ErrWrongApplicationID is gate 1.
	ErrWrongApplicationID = errors.New("not a WGVA database")

	// ErrSchemaTooNew is gate 2. sqlitemigration owns PRAGMA user_version and
	// does not itself reject a schema newer than the binary, so this gate is
	// ours and runs before the ladder does.
	ErrSchemaTooNew = errors.New("schema is newer than this binary supports")

	// ErrMalformedMetadata is gate 4.
	ErrMalformedMetadata = errors.New("world metadata is missing or malformed")

	// ErrWrongWorldRadius is gate 5.
	//
	// DESIGN.md 27.5 spells the sentinel ErrWrongComponentWidth and its message
	// "a different coordinate width". That name is left over from when the
	// radius was forced to be a storage type's maximum and the two were the same
	// fact. They are two decisions now (DESIGN.md 4.2), a width in bits does not
	// identify a world — 100000 and 131071 are different worlds and both are
	// eighteen bits — and AGENTS.md is explicit that gate 5 records the radius.
	// The gate is the one 27.5 describes; only the name follows the prose rather
	// than the code block. See appendix D.19.
	ErrWrongWorldRadius = errors.New("world was generated at a different world radius")

	// ErrUnsupportedGenVersion is gate 6's first half.
	//
	// A generator incompatibility is never handled by silently regenerating the
	// world under current rules. Every overlay coordinate would then point at
	// terrain that no longer exists there, silently, because a settlement is a
	// coordinate and a coordinate still resolves.
	ErrUnsupportedGenVersion = errors.New("world was generated by an algorithm version this binary cannot reproduce")

	// ErrFingerprintMismatch is gate 6's second half: the stored configuration
	// does not hash to the stored fingerprint.
	ErrFingerprintMismatch = errors.New("stored configuration does not match its fingerprint")

	// ErrInvalidConfig is gate 4's other half: the stored configuration is not
	// one this binary can generate a world from. A missing key is a refusal
	// naming it and never a zero value; DESIGN.md 21.1.
	ErrInvalidConfig = errors.New("stored configuration is not valid")

	// ErrBadCoordinate is returned for a stored (q, r) outside the canonical
	// domain.
	//
	// SQLite columns hold anything, so this is malformed data rather than a
	// distant tile. It is refused rather than passed through wgva.NewCoord,
	// which would silently relocate a player's settlement to a real coordinate
	// somewhere else. DESIGN.md 27.6.
	ErrBadCoordinate = errors.New("stored coordinate is outside the world")

	// ErrBadRotation is returned for a stored player rotation outside 0..5. It
	// is a typed refusal and never a FloorMod: a player's origin and rotation
	// are what every coordinate and heading they have ever been given mean, so
	// quietly repairing one would silently relabel all of it. DESIGN.md 28.
	ErrBadRotation = errors.New("stored player rotation is outside 0..5")
)

// OpenError carries the specifics and wraps one of the sentinels above.
//
// Found and Expected are the two numbers a gate compared, when the gate compared
// numbers; Detail is what it compared when they were not numbers. A caller
// matches on the sentinel and prints this.
type OpenError struct {
	Path     string
	Found    int64
	Expected int64
	Detail   string
	Err      error
}

func (e *OpenError) Error() string {
	var b string
	switch {
	case e.Detail != "":
		b = fmt.Sprintf("%v: %s", e.Err, e.Detail)
	case e.Found != 0 || e.Expected != 0:
		b = fmt.Sprintf("%v: found %d, expected %d", e.Err, e.Found, e.Expected)
	default:
		b = e.Err.Error()
	}
	if e.Path == "" {
		return b
	}
	return e.Path + ": " + b
}

func (e *OpenError) Unwrap() error { return e.Err }

// migrations is the schema ladder, in order.
//
// **Never edit a released migration.** The ladder is part of the file format;
// editing one changes what an existing file at that step means, and the step
// number that is supposed to say so does not move. Append instead.
//
// Every coordinate-keyed table is WITHOUT ROWID, which matters more than it
// looks: such a table *is* a B-tree keyed by the composite primary key, so
// loading every overlay in a viewport is one ordered range scan rather than a
// rowid lookup per row through a secondary index. That is the coordinate
// locality that would otherwise be the main reason to reach for a dedicated
// key-value store. See DESIGN.md 27.2 and appendix C.
//
// Columns are INTEGER whatever the world's size, because SQLite has one integer
// type and encodes a value in one to eight bytes by magnitude rather than by
// declared width. Neither the radius nor the storage type appears in the schema,
// so a radius change needs no migration — only the refusal at gate 5.
var migrations = []string{
	// 1. The world, the players, and the player overlays.
	`
CREATE TABLE world (
    id                INTEGER PRIMARY KEY CHECK (id = 1),
    seed              INTEGER NOT NULL,
    algorithm_version INTEGER NOT NULL,
    world_radius      INTEGER NOT NULL,
    configuration     TEXT    NOT NULL,
    fingerprint       TEXT    NOT NULL,
    created_build     TEXT    NOT NULL,
    created_at        TEXT    NOT NULL
);

CREATE TABLE player (
    id       TEXT    PRIMARY KEY,
    origin_q INTEGER NOT NULL,
    origin_r INTEGER NOT NULL,
    rotation INTEGER NOT NULL CHECK (rotation BETWEEN 0 AND 5)
);

CREATE TABLE overlay_discovered (
    q INTEGER NOT NULL,
    r INTEGER NOT NULL,
    PRIMARY KEY (q, r)
) WITHOUT ROWID;

CREATE TABLE overlay_settlement (
    q    INTEGER NOT NULL,
    r    INTEGER NOT NULL,
    name TEXT    NOT NULL,
    PRIMARY KEY (q, r)
) WITHOUT ROWID;

CREATE TABLE overlay_label (
    q    INTEGER NOT NULL,
    r    INTEGER NOT NULL,
    name TEXT    NOT NULL,
    PRIMARY KEY (q, r)
) WITHOUT ROWID;
`,
}

// SchemaVersion is the highest PRAGMA user_version this binary understands. It
// is the ladder's length, and gate 2 compares a file's against it.
func SchemaVersion() int64 { return int64(len(migrations)) }

// schema is what sqlitemigration runs.
func schema() sqlitemigration.Schema {
	return sqlitemigration.Schema{AppID: ApplicationID, Migrations: migrations}
}

// prepareConn is the connection preparation every connection gets, in tests
// exactly as in production.
//
// There are no foreign keys to generated data and there is no generated data in
// the file to point at — authoritative player state must never have a
// referential dependency on a discardable cache, because dropping the cache
// would then require dropping the player's settlements. The pragma is on anyway,
// so that a constraint deliberately added later between two authoritative tables
// is actually enforced. It has to be set on every connection, because SQLite
// defaults it off per connection; setting it in one place and not the other is
// how a constraint ends up enforced in production and ignored in tests, or the
// reverse. DESIGN.md 27.3.
func prepareConn(conn *sqlite.Conn) error {
	return sqlitex.ExecuteTransient(conn, "PRAGMA foreign_keys = ON;", nil)
}

// openFlags is how every connection to a world is opened.
//
// OpenCreate is absent, which is the whole point: only Create passes it, so
// every other path refuses a missing file at the operating system rather than
// quietly bringing one into existence. OpenWAL is absent too, and that is a
// decision rather than an omission — WAL writes a -wal and a -shm beside the
// database, and appendix C's argument is that a world is one file. Nothing here
// needs WAL's concurrency: the authoritative data is a metadata row and some
// sparse overlays, and the part that is actually hot, generation, touches no
// database at all.
const openFlags = sqlite.OpenReadWrite | sqlite.OpenURI

// pragmaInt reads one integer-valued pragma.
func pragmaInt(conn *sqlite.Conn, pragma string) (int64, error) {
	var value int64
	err := sqlitex.ExecuteTransient(conn, "PRAGMA "+pragma+";", &sqlitex.ExecOptions{
		ResultFunc: func(stmt *sqlite.Stmt) error {
			value = stmt.ColumnInt64(0)
			return nil
		},
	})
	if err != nil {
		return 0, fmt.Errorf("reading %s: %w", pragma, err)
	}
	return value, nil
}

// migrate is gate 3: apply the supported ordered migrations.
//
// It runs the ladder only when the ladder has something to do. That is not an
// optimization — sqlitemigration.Migrate writes PRAGMA application_id
// unconditionally, inside a savepoint, so calling it on an already-current file
// commits a write transaction and moves two bytes of the header every time a
// world is opened. Two tools here are documented as opening a world and not
// writing to it, a world file on read-only media would fail to open at all, and
// the assertion that a refused open leaves the file byte for byte identical is
// only worth making if a permitted open does too.
//
// The ladder itself is still sqlitemigration's. Writing a forty-line ladder by
// hand would be owning code for its own sake, and the rule that matters — the
// ladder is part of the file format and must not move because a dependency did —
// is served by pinning the version and by the tests of DESIGN.md 30.11.
func migrate(ctx context.Context, path string, schemaVersion int64, create bool) error {
	if !create && schemaVersion == SchemaVersion() {
		return nil
	}
	flags := openFlags
	if create {
		flags |= sqlite.OpenCreate
	}
	conn, err := sqlite.OpenConn(path, flags)
	if err != nil {
		return err
	}
	defer conn.Close()
	if err := prepareConn(conn); err != nil {
		return err
	}
	return sqlitemigration.Migrate(ctx, conn, schema())
}

// pool is the connection pool the application reads and writes through, with
// the one discipline DESIGN.md 27.7 asks for built into the only way to use it.
//
// A *sqlite.Conn must not be used concurrently, and every non-nil connection
// taken from a pool must be returned to that same pool including on the error
// paths. [pool.with] is the only accessor, so there is no path through this
// package where a connection is taken and a later edit can drop the return: the
// defer is written once, here, beside the Take it belongs to.
//
// It is sqlitex's pool rather than sqlitemigration's because the ladder has
// already run by the time one of these exists; sqlitemigration's pool would run
// it again on every connection it opens, which is the write described above.
type pool struct{ p *sqlitex.Pool }

// openPool opens the application pool. It never creates: by the time it is
// called the file exists, because gate 3 has already been through it.
func openPool(path string) (*pool, error) {
	p, err := sqlitex.NewPool(path, sqlitex.PoolOptions{
		Flags:       openFlags,
		PrepareConn: prepareConn,
	})
	if err != nil {
		return nil, err
	}
	return &pool{p: p}, nil
}

// with runs fn on one connection from the pool.
func (p *pool) with(ctx context.Context, fn func(*sqlite.Conn) error) error {
	conn, err := p.p.Take(ctx)
	if err != nil {
		return err
	}
	defer p.p.Put(conn)
	return fn(conn)
}

// Close releases the pool.
func (p *pool) Close() error { return p.p.Close() }
